spring:
  application:
    name: skate-inventory-mgmt-system
  datasource:
    url: jdbc:postgresql://localhost:5432/skatedb
    username: skate_user
    password: "!@#D3v3lop3r!@#"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # schema created manually
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: ALWAYS #Pretty Colors
logging:
  level:
    com:
      skillstorm: debug
