spring:
  application:
    name: skate-inventory-mgmt-system
  datasource:
    url: jdbc:h2:mem:skatedb
    username: sa
    password:
    driver-class-name: org.h2.Driver #JDBC connection driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: ALWAYS #Pretty Colors
logging:
  level:
    com:
      skillstorm: debug
